Ddcnl 3368
hmrc/state-pension pull request #113
Opened 2021-01-12 10:21 UTC by Dandyboyo2

2021-01-13 11:10 UTC, kurtlogan requested changes

2021-01-13 11:10 UTC, kurtlogan commented on app/uk/gov/hmrc/statepension/connectors/CitizenDetailsConnector.scala
> +import scala.concurrent.ExecutionContext.Implicits.global
EC should be injected in

2021-01-13 11:10 UTC, kurtlogan commented on app/uk/gov/hmrc/statepension/services/StatePensionService.scala
> +import scala.concurrent.ExecutionContext.Implicits.global
Inject in EC

2021-01-13 14:26 UTC, kurtlogan approved these changes

2021-01-14 09:43 UTC, pascal22p approved these changes

2021-01-14 09:43 UTC, pascal22p commented on app/uk/gov/hmrc/statepension/connectors/NpsConnector.scala
> +      HeaderCarrier(Some(Authorization(s"Bearer $token")), sessionId = headerCarrier.sessionId, requestId = headerCarrier.requestId)
That's perfect.

2021-01-14 11:00 UTC, merged